### ISSUE TITLE
Clean up ternary statements 

### ISSUE THREAD

**Issue by paul-barry-kenzan** [benmcosker/es6-angular-flickr#2]
When using ternary statements to set values, the declaration should be on the left, with ternary condition on the right.

```javascript
var myValue = (isTrue) ? 'true value' : 'false value';
```

**Comment by benmcosker** [comment]
addressed in commit:
761bc1b22a09b77506e179387e92541265f9034e

**Comment by paul-barry-kenzan** [comment]
@benmcosker 
Just a tip, and certainly not necessary to go back to previous PRs/Issues, but [GitHub allows auto-closing of issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/).

So, if a single commit, or better yet, a PR is created to resolve a specific issue, by including one of the [GitHub keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues), the issue will be closed. This ensures a 1:1 reference between PRs and the issues they resolve.

For example, to resolve this issue (#2) a PR title may be:

> `Fix #2: Refactor ternary statements`
